spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"